-- Seed data for MDLBEAST Communications System
-- Note: Admin and Test users are now created from environment variables:
-- - SUPER_ADMIN_EMAIL / SUPER_ADMIN_PASSWORD / SUPER_ADMIN_NAME
-- - TEST_USER_EMAIL / TEST_USER_PASSWORD / TEST_USER_NAME
-- No hardcoded users in this file for security reasons.
